fieldLayouts:
  4a700090-db2f-4939-bba5-25774f989aca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d0fcdb2a-17db-4d73-85a3-7f234d9b21e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c22e4947-7fbb-488a-994f-246c31e27b95 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8505d8d9-cd65-4f4a-9305-147e1653a264
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c430001c-4bfc-4154-9e13-f5ada3b4a22d # Text
            instructions: 'Credits to be displayed in the investigation menu'
            label: Acknowledgements
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eed660e-5ef1-4664-a283-9988b8d53e7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ed72b51-65ac-4bd9-964e-939ccf54eeff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b13f4459-60b8-4556-8f68-38f7bcf4f5cb # Assessments
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 637a52b1-6681-4aff-8a64-7a3db2c4f6fa
            userCondition: null
            warning: null
            width: 100
        name: Assessments
        uid: 32cf716f-eae5-4588-9da5-8947c2a13781
        userCondition: null
handle: investigationParent
hasTitleField: true
name: 'Investigation (Parent Entry)'
section: 1a93d10f-deca-4e6b-a3e8-9baae53e7c47 # Investigations
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
