fieldLayouts:
  f36eac86-b105-4069-8d58-ffc0f75df690:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be96be44-8356-4939-8de9-ad492dafa366
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\TypeConditionRule
                  operator: in
                  uid: aaae784c-03d3-4330-bb68-cd223dd56cd7
                  values:
                    - 16d66db4-47e3-4e22-a040-357377f43cb0 # Sortable Table
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: a4afde15-f983-4c30-b0d7-e0b56871e4de # Dataset
            instructions: null
            label: 'Sortable Table Dataset'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ee0878e-3fd8-4b8b-bad6-456749fc504c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b892cc99-c162-4e2d-96c5-656cc5c52c7c
        userCondition: null
handle: sortableTable
hasTitleField: true
name: 'Sortable Table'
section: 28704998-935a-423b-a405-d4ad8b38efa2 # Widgets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
