columnSuffix: null
contentColumnType: string
fieldGroup: 5599d188-862e-4717-b206-6aadd975c937 # Common
handle: complexTable
instructions: null
name: 'Complex Table'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1858920766
  columns:
    __assoc__:
      -
        - e7468177-b56b-4fbc-8ca0-af8c830cabef # Table Row
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_complextable}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
