columnSuffix: gnysmpyf
contentColumnType: text
fieldGroup: 074f7db9-8ff3-4016-ad34-bfe9c31d5543 # Pages
handle: description
instructions: "Good descriptions play a crucial role in search engine rankings and are among the first things people see in a search or link preview.\r\n\r\nWrite a unique description related to the page’s content between 120-160 characters, use active language, and include a call to action where possible (e.g. “Explore...“, “Read about…“, “Learn…“)."
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
