columnSuffix: null
contentColumnType: string
fieldGroup: 4e1884f2-7cc9-40d8-8426-f66da625d8cc # Assets
handle: histogramDatasets
instructions: null
name: Datasets
searchable: true
settings:
  contentTable: '{{%matrixcontent_histogramdatasets}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
