columnSuffix: null
contentColumnType: string
fieldGroup: 5dc7dc5c-2390-4eb4-9714-818aa35f5772 # Investigations
handle: investigationEntry
instructions: null
name: Investigation
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\LevelConditionRule
              -
                - uid
                - 4ad4dbb5-8eac-47c2-9660-8a75f38fba2d
              -
                - operator
                - '='
              -
                - value
                - '1'
              -
                - maxValue
                - ''
              -
                - step
                - 1
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:1a93d10f-deca-4e6b-a3e8-9baae53e7c47' # Investigations
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
