columnSuffix: null
contentColumnType: string
fieldGroup: 5dc7dc5c-2390-4eb4-9714-818aa35f5772 # Investigations
handle: landingNavigation
instructions: null
name: 'Landing Navigation'
searchable: true
settings:
  contentTable: '{{%matrixcontent_landingnavigation}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
