columnSuffix: null
contentColumnType: string
fieldGroup: 5dc7dc5c-2390-4eb4-9714-818aa35f5772 # Investigations
handle: relatedAssessments
instructions: null
name: Assessments
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:f8b60baf-40d3-4cc6-9384-eecd53594755' # Assessments
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
