columnSuffix: null
contentColumnType: string
fieldGroup: 5599d188-862e-4717-b206-6aadd975c937 # Common
handle: simpleTable
instructions: null
name: 'Simple Table'
searchable: false
settings:
  contentTable: '{{%matrixcontent_simpletable}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
