columnSuffix: xfcchvsu
contentColumnType: text
fieldGroup: 074f7db9-8ff3-4016-ad34-bfe9c31d5543 # Pages
handle: subHeroText
instructions: null
name: 'Sub Hero Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
